In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime

In [1]:
import seaborn as sns
!pip install scikit-learn
import matplotlib.pyplot as plt

Requirement already satisfied: scikit-learn in c:\users\l\anaconda3\lib\site-packages (0.24.2)
Requirement already satisfied: numpy>=1.13.3 in c:\users\l\anaconda3\lib\site-packages (from scikit-learn) (1.20.3)
Requirement already satisfied: joblib>=0.11 in c:\users\l\anaconda3\lib\site-packages (from scikit-learn) (1.1.0)
Requirement already satisfied: scipy>=0.19.1 in c:\users\l\anaconda3\lib\site-packages (from scikit-learn) (1.7.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\l\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)

In [210]:
import pandas as pd
import datetime
import time
import collections

df = pd.read_csv('probe.txt',names=['feed_id', 'zone_id','status','Time'], header=None)



#df
#sorted_df = df.sort_values(by=['feed_id'] , ascending=True)
#pd.set_option('display.max_rows', 1762)
#sorted_df

#gp=df.groupby(["feed_id",'zone_id'])
#for name, group in df.groupby(["feed_id",'zone_id']):
    #print(name)
    #print(group)

#grouped_index = df.apply(lambda x: x.reset_index(drop = True)).reset_index()
#grouped_index

#for name, group in df.groupby(["feed_id","zone_id"]):
#    print(df)

grouped_df = df.groupby(["feed_id","zone_id"])

for key,item in grouped_df:
    a_group = grouped_df.get_group(key)
    a_group.reset_index(drop=True, inplace=True)
    print(key)
    print(a_group)
    

#type(a_group)
#gp.first()
#gp
#type(gp)
#x=[gp.get_group(x) for x in gp.groups]
#type(x)

(1, 3)
   feed_id  zone_id status                     Time
0        1        3     in  2022-05-15 09:10:57.328
1        1        3    out  2022-05-15 09:11:01.909
2        1        3     in  2022-05-15 09:11:39.096
3        1        3    out  2022-05-15 09:11:53.448
(1, 4)
    feed_id  zone_id status                     Time
0         1        4     in  2022-05-15 08:49:40.525
1         1        4    out  2022-05-15 08:49:40.889
2         1        4     in  2022-05-15 08:49:41.056
3         1        4    out  2022-05-15 08:51:05.437
4         1        4     in  2022-05-15 08:51:05.497
5         1        4    out  2022-05-15 08:51:21.059
6         1        4     in  2022-05-15 08:51:26.089
7         1        4    out  2022-05-15 08:51:42.408
8         1        4     in  2022-05-15 08:51:42.566
9         1        4    out  2022-05-15 08:51:42.740
10        1        4     in  2022-05-15 09:06:12.166
11        1        4    out  2022-05-15 09:07:20.658
12        1        4     in  2022-05-15 09:07:20.926
13        1        4    out  2022-05-15 09:07:23.007
14        1        4     in  2022-05-15 09:07:23.230
15        1        4    out  2022-05-15 09:07:30.496
16        1        4     in  2022-05-15 09:07:30.777
17        1        4    out  2022-05-15 09:07:35.663
18        1        4     in  2022-05-15 09:07:36.733
19        1        4    out  2022-05-15 09:07:37.033
20        1        4     in  2022-05-15 09:08:43.326
21        1        4    out  2022-05-15 09:09:00.656
(1, 6)
    feed_id  zone_id status                     Time
0         1        6    out  2022-05-15 08:45:11.465
1         1        6     in  2022-05-15 08:45:12.259
2         1        6    out  2022-05-15 08:49:21.542
3         1        6     in  2022-05-15 08:49:24.953
4         1        6    out  2022-05-15 08:49:25.426
5         1        6     in  2022-05-15 08:49:25.709
6         1        6    out  2022-05-15 08:49:27.986
7         1        6     in  2022-05-15 08:52:16.024
8         1        6    out  2022-05-15 08:52:36.061
9         1        6     in  2022-05-15 08:52:51.911
10        1        6    out  2022-05-15 08:53:07.417
11        1        6     in  2022-05-15 08:53:07.871
12        1        6    out  2022-05-15 08:53:17.194
13        1        6     in  2022-05-15 08:53:17.336
14        1        6    out  2022-05-15 08:53:33.643
15        1        6     in  2022-05-15 08:53:36.392
16        1        6    out  2022-05-15 08:53:48.180
17        1        6     in  2022-05-15 08:53:50.877
18        1        6    out  2022-05-15 08:54:43.550
19        1        6     in  2022-05-15 08:54:44.090
20        1        6    out  2022-05-15 08:55:10.046
21        1        6     in  2022-05-15 08:55:12.764
22        1        6    out  2022-05-15 08:55:12.910
23        1        6     in  2022-05-15 08:55:13.084
24        1        6    out  2022-05-15 08:56:06.517
25        1        6     in  2022-05-15 08:56:06.940
26        1        6    out  2022-05-15 08:58:38.435
27        1        6     in  2022-05-15 08:58:38.504
28        1        6    out  2022-05-15 08:58:39.086
29        1        6     in  2022-05-15 08:58:41.655
30        1        6    out  2022-05-15 08:58:55.158
31        1        6     in  2022-05-15 08:59:00.869
32        1        6    out  2022-05-15 09:00:52.267
33        1        6     in  2022-05-15 09:00:52.573
34        1        6    out  2022-05-15 09:02:08.078
35        1        6     in  2022-05-15 09:02:08.243
36        1        6    out  2022-05-15 09:02:08.903
37        1        6     in  2022-05-15 09:02:09.510
38        1        6    out  2022-05-15 09:02:14.173
39        1        6     in  2022-05-15 09:02:15.195
40        1        6    out  2022-05-15 09:02:17.687
41        1        6     in  2022-05-15 09:02:17.765
42        1        6    out  2022-05-15 09:02:18.960
43        1        6     in  2022-05-15 09:02:28.532
44        1        6    out  2022-05-15 09:02:39.946
45        1        6     in  2022-05-15 09:02:40.679
46        1        6    out  2022-05-15 09:02:51.321
47        1        6     in  2022-05-15 09:02:51.386
48        1        6    out  2022-05-15 09:03:21.153
49        1        6     in  2022-05-15 09:03:21.605
50        1        6    out  2022-05-15 09:03:21.679
51        1        6     in  2022-05-15 09:03:22.081
52        1        6    out  2022-05-15 09:03:22.852
53        1        6     in  2022-05-15 09:03:23.198
54        1        6    out  2022-05-15 09:03:27.559
55        1        6     in  2022-05-15 09:03:27.685
56        1        6    out  2022-05-15 09:03:36.718
57        1        6     in  2022-05-15 09:03:39.536
58        1        6    out  2022-05-15 09:03:41.776
59        1        6     in  2022-05-15 09:09:32.958
60        1        6    out  2022-05-15 09:10:09.033
61        1        6     in  2022-05-15 09:10:09.093
62        1        6    out  2022-05-15 09:10:11.684
63        1        6     in  2022-05-15 09:10:35.548
64        1        6    out  2022-05-15 09:10:35.606
65        1        6     in  2022-05-15 09:12:30.441
66        1        6    out  2022-05-15 09:12:41.672
67        1        6     in  2022-05-15 09:12:41.795
68        1        6    out  2022-05-15 09:12:50.857
69        1        6     in  2022-05-15 09:12:51.036
70        1        6    out  2022-05-15 09:12:55.071
71        1        6     in  2022-05-15 09:12:55.165
72        1        6    out  2022-05-15 09:14:45.871
73        1        6     in  2022-05-15 09:14:46.251
74        1        6    out  2022-05-15 09:14:46.402
75        1        6     in  2022-05-15 09:14:46.516
76        1        6    out  2022-05-15 09:14:48.122
77        1        6     in  2022-05-15 09:14:48.260
(1, 7)
    feed_id  zone_id status                     Time
0         1        7     in  2022-05-15 09:03:45.937
1         1        7    out  2022-05-15 09:03:46.468
2         1        7     in  2022-05-15 09:05:14.678
3         1        7    out  2022-05-15 09:05:15.741
4         1        7     in  2022-05-15 09:05:18.152
5         1        7    out  2022-05-15 09:05:39.499
6         1        7     in  2022-05-15 09:05:39.699
7         1        7    out  2022-05-15 09:05:42.430
8         1        7     in  2022-05-15 09:05:47.232
9         1        7    out  2022-05-15 09:05:47.411
10        1        7     in  2022-05-15 09:05:47.606
11        1        7    out  2022-05-15 09:05:47.646
12        1        7     in  2022-05-15 09:05:47.768
13        1        7    out  2022-05-15 09:05:47.855
14        1        7     in  2022-05-15 09:08:04.475
15        1        7    out  2022-05-15 09:08:04.796
16        1        7     in  2022-05-15 09:08:05.099
17        1        7    out  2022-05-15 09:08:05.210
18        1        7     in  2022-05-15 09:08:05.632
19        1        7    out  2022-05-15 09:08:14.763
20        1        7     in  2022-05-15 09:08:17.489
21        1        7    out  2022-05-15 09:08:18.635
22        1        7     in  2022-05-15 09:08:18.779
23        1        7    out  2022-05-15 09:08:18.989
24        1        7     in  2022-05-15 09:08:19.151
25        1        7    out  2022-05-15 09:08:19.291
26        1        7     in  2022-05-15 09:08:20.150
27        1        7    out  2022-05-15 09:08:21.382
28        1        7     in  2022-05-15 09:08:22.104
29        1        7    out  2022-05-15 09:08:22.670
(1, 8)
   feed_id  zone_id status                     Time
0        1        8     in  2022-05-15 09:03:52.765
1        1        8    out  2022-05-15 09:03:53.659
2        1        8     in  2022-05-15 09:03:56.987
3        1        8    out  2022-05-15 09:03:57.187
(8, 3)
   feed_id  zone_id status                     Time
0        8        3     in  2022-05-15 09:03:16.234
1        8        3    out  2022-05-15 09:04:34.709
(8, 4)
   feed_id  zone_id status                     Time
0        8        4     in  2022-05-15 09:03:11.534
1        8        4    out  2022-05-15 09:03:12.350
(8, 5)
   feed_id  zone_id status                     Time
0        8        5     in  2022-05-15 09:14:42.871
1        8        5    out  2022-05-15 09:14:44.306
2        8        5     in  2022-05-15 09:14:47.911
3        8        5    out  2022-05-15 09:14:48.189
4        8        5     in  2022-05-15 09:14:48.396
5        8        5    out  2022-05-15 09:14:48.647
(8, 7)
    feed_id  zone_id status                     Time
0         8        7     in  2022-05-15 09:05:05.921
1         8        7    out  2022-05-15 09:07:36.235
2         8        7     in  2022-05-15 09:07:45.669
3         8        7    out  2022-05-15 09:07:46.751
4         8        7     in  2022-05-15 09:08:04.775
5         8        7    out  2022-05-15 09:10:58.086
6         8        7     in  2022-05-15 09:10:58.194
7         8        7    out  2022-05-15 09:11:02.319
8         8        7     in  2022-05-15 09:11:02.387
9         8        7    out  2022-05-15 09:11:02.833
10        8        7     in  2022-05-15 09:11:04.104
11        8        7    out  2022-05-15 09:11:06.724
12        8        7     in  2022-05-15 09:11:06.804
13        8        7    out  2022-05-15 09:11:09.675
14        8        7     in  2022-05-15 09:11:17.106
15        8        7    out  2022-05-15 09:11:41.495
16        8        7     in  2022-05-15 09:11:41.671
17        8        7    out  2022-05-15 09:11:46.122
18        8        7     in  2022-05-15 09:11:46.271
19        8        7    out  2022-05-15 09:11:53.183
20        8        7     in  2022-05-15 09:11:53.704
21        8        7    out  2022-05-15 09:12:33.657
22        8        7     in  2022-05-15 09:12:55.710
23        8        7    out  2022-05-15 09:12:55.891
24        8        7     in  2022-05-15 09:14:55.295
25        8        7    out  2022-05-15 09:14:58.509
26        8        7     in  2022-05-15 09:14:59.234
27        8        7    out  2022-05-15 09:15:01.099
28        8        7     in  2022-05-15 09:15:04.359
29        8        7    out  2022-05-15 09:15:05.063
30        8        7     in  2022-05-15 09:15:05.223
31        8        7    out  2022-05-15 09:15:17.053
(8, 8)
    feed_id  zone_id status                     Time
0         8        8     in  2022-05-15 08:45:37.422
1         8        8    out  2022-05-15 08:50:02.713
2         8        8     in  2022-05-15 08:50:02.874
3         8        8    out  2022-05-15 09:01:44.237
4         8        8     in  2022-05-15 09:01:46.859
5         8        8    out  2022-05-15 09:01:47.144
6         8        8     in  2022-05-15 09:01:48.457
7         8        8    out  2022-05-15 09:01:48.572
8         8        8     in  2022-05-15 09:01:48.745
9         8        8    out  2022-05-15 09:01:49.546
10        8        8     in  2022-05-15 09:01:50.277
11        8        8    out  2022-05-15 09:01:51.555
12        8        8     in  2022-05-15 09:02:00.516
13        8        8    out  2022-05-15 09:02:00.848
14        8        8     in  2022-05-15 09:02:01.019
15        8        8    out  2022-05-15 09:02:01.117
16        8        8     in  2022-05-15 09:02:11.241
17        8        8    out  2022-05-15 09:02:11.670
18        8        8     in  2022-05-15 09:02:12.266
19        8        8    out  2022-05-15 09:02:37.953
20        8        8     in  2022-05-15 09:02:41.825
21        8        8    out  2022-05-15 09:02:42.765
22        8        8     in  2022-05-15 09:02:46.827
23        8        8    out  2022-05-15 09:02:46.966
24        8        8     in  2022-05-15 09:04:58.612
25        8        8    out  2022-05-15 09:05:04.621
26        8        8     in  2022-05-15 09:07:36.624
27        8        8    out  2022-05-15 09:07:37.779
28        8        8     in  2022-05-15 09:07:38.093
29        8        8    out  2022-05-15 09:07:40.753
30        8        8     in  2022-05-15 09:07:41.615
31        8        8    out  2022-05-15 09:07:44.371
32        8        8     in  2022-05-15 09:08:04.015
33        8        8    out  2022-05-15 09:08:04.308
(8, 9)
   feed_id  zone_id status                     Time
0        8        9     in  2022-05-15 09:03:05.275
1        8        9    out  2022-05-15 09:03:06.069
2        8        9     in  2022-05-15 09:04:47.520
3        8        9    out  2022-05-15 09:04:47.666
(9, 3)
    feed_id  zone_id status                     Time
0         9        3    out  2022-05-15 08:48:53.803
1         9        3     in  2022-05-15 08:48:54.003
2         9        3    out  2022-05-15 08:53:30.652
3         9        3     in  2022-05-15 08:53:30.769
4         9        3    out  2022-05-15 09:00:28.062
5         9        3     in  2022-05-15 09:00:29.014
6         9        3    out  2022-05-15 09:01:27.363
7         9        3     in  2022-05-15 09:01:27.451
8         9        3    out  2022-05-15 09:01:59.326
9         9        3     in  2022-05-15 09:02:01.509
10        9        3    out  2022-05-15 09:03:45.459
11        9        3     in  2022-05-15 09:05:38.440
12        9        3    out  2022-05-15 09:05:46.218
13        9        3     in  2022-05-15 09:05:46.406
14        9        3    out  2022-05-15 09:08:36.305
15        9        3     in  2022-05-15 09:12:17.423
16        9        3    out  2022-05-15 09:12:21.641
17        9        3     in  2022-05-15 09:12:23.981
(9, 4)
   feed_id  zone_id status                     Time
0        9        4     in  2022-05-15 09:05:17.096
1        9        4    out  2022-05-15 09:05:19.492
2        9        4     in  2022-05-15 09:05:19.624
3        9        4    out  2022-05-15 09:05:30.825
(9, 5)
    feed_id  zone_id status                     Time
0         9        5     in  2022-05-15 09:04:02.846
1         9        5    out  2022-05-15 09:04:47.135
2         9        5     in  2022-05-15 09:04:49.323
3         9        5    out  2022-05-15 09:04:57.677
4         9        5     in  2022-05-15 09:04:57.898
5         9        5    out  2022-05-15 09:05:01.663
6         9        5     in  2022-05-15 09:05:01.878
7         9        5    out  2022-05-15 09:05:01.942
8         9        5     in  2022-05-15 09:08:52.662
9         9        5    out  2022-05-15 09:09:03.557
10        9        5     in  2022-05-15 09:09:22.001
11        9        5    out  2022-05-15 09:10:02.398
12        9        5     in  2022-05-15 09:10:03.161
13        9        5    out  2022-05-15 09:10:14.471
14        9        5     in  2022-05-15 09:10:15.951
15        9        5    out  2022-05-15 09:10:19.742
16        9        5     in  2022-05-15 09:10:20.120
17        9        5    out  2022-05-15 09:10:27.223
18        9        5     in  2022-05-15 09:10:27.694
19        9        5    out  2022-05-15 09:10:44.324
20        9        5     in  2022-05-15 09:10:44.411
21        9        5    out  2022-05-15 09:10:48.376
22        9        5     in  2022-05-15 09:10:49.465
23        9        5    out  2022-05-15 09:10:52.877
24        9        5     in  2022-05-15 09:10:53.086
25        9        5    out  2022-05-15 09:10:56.398
26        9        5     in  2022-05-15 09:10:56.718
27        9        5    out  2022-05-15 09:11:24.313
28        9        5     in  2022-05-15 09:11:24.557
29        9        5    out  2022-05-15 09:11:28.214
30        9        5     in  2022-05-15 09:11:30.345
31        9        5    out  2022-05-15 09:11:31.514
32        9        5     in  2022-05-15 09:11:31.654
33        9        5    out  2022-05-15 09:11:31.781
34        9        5     in  2022-05-15 09:11:31.819
35        9        5    out  2022-05-15 09:11:40.035
36        9        5     in  2022-05-15 09:11:40.395
37        9        5    out  2022-05-15 09:11:41.155
38        9        5     in  2022-05-15 09:11:42.137
39        9        5    out  2022-05-15 09:11:59.780
(12, 3)
   feed_id  zone_id status                     Time
0       12        3     in  2022-05-15 08:46:22.438
1       12        3    out  2022-05-15 08:46:36.725
(12, 4)
    feed_id  zone_id status                     Time
0        12        4     in  2022-05-15 08:46:41.955
1        12        4    out  2022-05-15 08:46:42.436
2        12        4     in  2022-05-15 08:46:42.481
3        12        4    out  2022-05-15 08:47:11.126
4        12        4     in  2022-05-15 08:47:11.176
5        12        4    out  2022-05-15 08:47:19.127
6        12        4     in  2022-05-15 08:47:19.207
7        12        4    out  2022-05-15 08:47:20.139
8        12        4     in  2022-05-15 08:47:20.711
9        12        4    out  2022-05-15 08:47:25.758
10       12        4     in  2022-05-15 08:47:25.960
11       12        4    out  2022-05-15 08:47:31.808
12       12        4     in  2022-05-15 08:47:31.881
13       12        4    out  2022-05-15 08:47:56.775
14       12        4     in  2022-05-15 08:47:57.094
15       12        4    out  2022-05-15 08:47:57.266
16       12        4     in  2022-05-15 08:47:57.934
17       12        4    out  2022-05-15 08:48:21.083
18       12        4     in  2022-05-15 08:48:21.808
19       12        4    out  2022-05-15 08:48:53.732
20       12        4     in  2022-05-15 08:48:53.904
21       12        4    out  2022-05-15 08:49:41.291
22       12        4     in  2022-05-15 08:49:41.453
23       12        4    out  2022-05-15 08:50:03.757
24       12        4     in  2022-05-15 08:50:09.024
25       12        4    out  2022-05-15 08:50:51.628
26       12        4     in  2022-05-15 08:50:51.863
27       12        4    out  2022-05-15 08:54:58.518
28       12        4     in  2022-05-15 08:54:58.739
29       12        4    out  2022-05-15 08:56:56.166
30       12        4     in  2022-05-15 08:56:56.296
31       12        4    out  2022-05-15 08:57:18.631
32       12        4     in  2022-05-15 08:57:18.774
33       12        4    out  2022-05-15 08:57:50.156
34       12        4     in  2022-05-15 08:57:50.431
35       12        4    out  2022-05-15 08:57:50.844
36       12        4     in  2022-05-15 08:57:51.244
37       12        4    out  2022-05-15 08:58:04.694
38       12        4     in  2022-05-15 08:58:07.874
39       12        4    out  2022-05-15 08:58:08.197
40       12        4     in  2022-05-15 08:58:09.077
41       12        4    out  2022-05-15 08:58:35.522
42       12        4     in  2022-05-15 08:58:35.691
43       12        4    out  2022-05-15 08:58:49.259
44       12        4     in  2022-05-15 08:58:49.713
45       12        4    out  2022-05-15 08:58:51.065
46       12        4     in  2022-05-15 08:58:51.411
47       12        4    out  2022-05-15 08:59:23.018
48       12        4     in  2022-05-15 08:59:23.093
49       12        4    out  2022-05-15 08:59:28.624
50       12        4     in  2022-05-15 08:59:30.533
51       12        4    out  2022-05-15 09:02:51.406
52       12        4     in  2022-05-15 09:02:56.994
53       12        4    out  2022-05-15 09:03:00.248
54       12        4     in  2022-05-15 09:03:01.548
55       12        4    out  2022-05-15 09:03:47.737
56       12        4     in  2022-05-15 09:03:48.017
57       12        4    out  2022-05-15 09:04:23.542
58       12        4     in  2022-05-15 09:04:24.390
59       12        4    out  2022-05-15 09:04:25.548
60       12        4     in  2022-05-15 09:04:26.003
61       12        4    out  2022-05-15 09:04:29.187
62       12        4     in  2022-05-15 09:04:29.347
63       12        4    out  2022-05-15 09:04:39.245
64       12        4     in  2022-05-15 09:04:39.375
65       12        4    out  2022-05-15 09:05:07.535
66       12        4     in  2022-05-15 09:05:07.633
67       12        4    out  2022-05-15 09:05:21.412
68       12        4     in  2022-05-15 09:05:21.958
69       12        4    out  2022-05-15 09:05:23.293
70       12        4     in  2022-05-15 09:05:24.153
71       12        4    out  2022-05-15 09:05:39.047
72       12        4     in  2022-05-15 09:05:39.257
73       12        4    out  2022-05-15 09:08:39.346
74       12        4     in  2022-05-15 09:08:39.661
75       12        4    out  2022-05-15 09:09:15.781
(12, 5)
    feed_id  zone_id status                     Time

In [224]:
a_group = a_group.sort_values('Time')
assert(a_group.loc[0, 'status'] == 'in')
for i, row in a_group.iterrows():
    if row['status'] == 'in':
        j = i
    else:
        assert(row['status'] == 'out')
        assert(i == j+1)
        a_group.loc[j, 'Time out'] = row['Time']

In [233]:
in_time = a_group[a_group['status'] == 'in'].reset_index()
out_time = a_group[a_group['status'] == 'out'].reset_index()
assert(in_time.shape == out_time.shape)
in_time.rename(columns = {'Time': 'In Time'}, inplace = True)
out_time.rename(columns = {'Time': 'Out Time'}, inplace = True)

In [234]:
pd.concat([in_time['In Time'], out_time['Out Time']], axis = 1)

                   In Time                 Out Time
0  2022-05-15 09:14:41.041  2022-05-15 09:15:02.350
1  2022-05-15 09:15:03.019  2022-05-15 09:15:03.210

In [168]:
from datetime import datetime

total_diff = 0
date_format_str = '%Y-%m-%d %H:%M:%S.%f'

In [241]:
time_in_out = pd.DataFrame([])
for key, item in grouped_df:
    a_group = grouped_df.get_group(key)
    a_group = a_group.sort_values('Time')
    a_group.reset_index(drop=True, inplace=True)
    j = None
#    assert(a_group.loc[0, 'status'] == 'in')
    for i, row in a_group.iterrows():
        if row['status'] == 'in':
            j = i
        else:
            assert(row['status'] == 'out')
            if j is None:
                continue
            assert(i == j+1)
            a_group.loc[j, 'Time out'] = row['Time']      
    time_in_out = time_in_out.append(a_group[a_group['status'] == 'in'])

In [244]:
time_in_out['Time out'] = pd.to_datetime(time_in_out['Time out'])
time_in_out['Time'] = pd.to_datetime(time_in_out['Time'])

In [245]:
time_in_out['diff'] = time_in_out['Time out'] - time_in_out['Time']

In [254]:
time_in_out

,feed_id,zone_id,status,Time,Time out,diff
0,1,3,in,2022-05-15 09:10:57.328,2022-05-15 09:11:01.909,0 days 00:00:04.581000
2,1,3,in,2022-05-15 09:11:39.096,2022-05-15 09:11:53.448,0 days 00:00:14.352000
0,1,4,in,2022-05-15 08:49:40.525,2022-05-15 08:49:40.889,0 days 00:00:00.364000
2,1,4,in,2022-05-15 08:49:41.056,2022-05-15 08:51:05.437,0 days 00:01:24.381000
4,1,4,in,2022-05-15 08:51:05.497,2022-05-15 08:51:21.059,0 days 00:00:15.562000
6,1,4,in,2022-05-15 08:51:26.089,2022-05-15 08:51:42.408,0 days 00:00:16.319000
8,1,4,in,2022-05-15 08:51:42.566,2022-05-15 08:51:42.740,0 days 00:00:00.174000
10,1,4,in,2022-05-15 09:06:12.166,2022-05-15 09:07:20.658,0 days 00:01:08.492000
12,1,4,in,2022-05-15 09:07:20.926,2022-05-15 09:07:23.007,0 days 00:00:02.081000
14,1,4,in,2022-05-15 09:07:23.230,2022-05-15 09:07:30.496,0 days 00:00:07.266000
16,1,4,in,2022-05-15 09:07:30.777,2022-05-15 09:07:35.663,0 days 00:00:04.886000
18,1,4,in,2022-05-15 09:07:36.733,2022-05-15 09:07:37.033,0 days 00:00:00.300000
20,1,4,in,2022-05-15 09:08:43.326,2022-05-15 09:09:00.656,0 days 00:00:17.330000
1,1,6,in,2022-05-15 08:45:12.259,2022-05-15 08:49:21.542,0 days 00:04:09.283000
3,1,6,in,2022-05-15 08:49:24.953,2022-05-15 08:49:25.426,0 days 00:00:00.473000
5,1,6,in,2022-05-15 08:49:25.709,2022-05-15 08:49:27.986,0 days 00:00:02.277000
7,1,6,in,2022-05-15 08:52:16.024,2022-05-15 08:52:36.061,0 days 00:00:20.037000
9,1,6,in,2022-05-15 08:52:51.911,2022-05-15 08:53:07.417,0 days 00:00:15.506000
11,1,6,in,2022-05-15 08:53:07.871,2022-05-15 08:53:17.194,0 days 00:00:09.323000
13,1,6,in,2022-05-15 08:53:17.336,2022-05-15 08:53:33.643,0 days 00:00:16.307000
15,1,6,in,2022-05-15 08:53:36.392,2022-05-15 08:53:48.180,0 days 00:00:11.788000
17,1,6,in,2022-05-15 08:53:50.877,2022-05-15 08:54:43.550,0 days 00:00:52.673000
19,1,6,in,2022-05-15 08:54:44.090,2022-05-15 08:55:10.046,0 days 00:00:25.956000
21,1,6,in,2022-05-15 08:55:12.764,2022-05-15 08:55:12.910,0 days 00:00:00.146000
23,1,6,in,2022-05-15 08:55:13.084,2022-05-15 08:56:06.517,0 days 00:00:53.433000
25,1,6,in,2022-05-15 08:56:06.940,2022-05-15 08:58:38.435,0 days 00:02:31.495000
27,1,6,in,2022-05-15 08:58:38.504,2022-05-15 08:58:39.086,0 days 00:00:00.582000
29,1,6,in,2022-05-15 08:58:41.655,2022-05-15 08:58:55.158,0 days 00:00:13.503000
31,1,6,in,2022-05-15 08:59:00.869,2022-05-15 09:00:52.267,0 days 00:01:51.398000
33,1,6,in,2022-05-15 09:00:52.573,2022-05-15 09:02:08.078,0 days 00:01:15.505000
35,1,6,in,2022-05-15 09:02:08.243,2022-05-15 09:02:08.903,0 days 00:00:00.660000
37,1,6,in,2022-05-15 09:02:09.510,2022-05-15 09:02:14.173,0 days 00:00:04.663000
39,1,6,in,2022-05-15 09:02:15.195,2022-05-15 09:02:17.687,0 days 00:00:02.492000
41,1,6,in,2022-05-15 09:02:17.765,2022-05-15 09:02:18.960,0 days 00:00:01.195000
43,1,6,in,2022-05-15 09:02:28.532,2022-05-15 09:02:39.946,0 days 00:00:11.414000
45,1,6,in,2022-05-15 09:02:40.679,2022-05-15 09:02:51.321,0 days 00:00:10.642000
47,1,6,in,2022-05-15 09:02:51.386,2022-05-15 09:03:21.153,0 days 00:00:29.767000
49,1,6,in,2022-05-15 09:03:21.605,2022-05-15 09:03:21.679,0 days 00:00:00.074000
51,1,6,in,2022-05-15 09:03:22.081,2022-05-15 09:03:22.852,0 days 00:00:00.771000
53,1,6,in,2022-05-15 09:03:23.198,2022-05-15 09:03:27.559,0 days 00:00:04.361000
55,1,6,in,2022-05-15 09:03:27.685,2022-05-15 09:03:36.718,0 days 00:00:09.033000
57,1,6,in,2022-05-15 09:03:39.536,2022-05-15 09:03:41.776,0 days 00:00:02.240000
59,1,6,in,2022-05-15 09:09:32.958,2022-05-15 09:10:09.033,0 days 00:00:36.075000
61,1,6,in,2022-05-15 09:10:09.093,2022-05-15 09:10:11.684,0 days 00:00:02.591000
63,1,6,in,2022-05-15 09:10:35.548,2022-05-15 09:10:35.606,0 days 00:00:00.058000
65,1,6,in,2022-05-15 09:12:30.441,2022-05-15 09:12:41.672,0 days 00:00:11.231000
67,1,6,in,2022-05-15 09:12:41.795,2022-05-15 09:12:50.857,0 days 00:00:09.062000
69,1,6,in,2022-05-15 09:12:51.036,2022-05-15 09:12:55.071,0 days 00:00:04.035000
71,1,6,in,2022-05-15 09:12:55.165,2022-05-15 09:14:45.871,0 days 00:01:50.706000
73,1,6,in,2022-05-15 09:14:46.251,2022-05-15 09:14:46.402,0 days 00:00:00.151000
75,1,6,in,2022-05-15 09:14:46.516,2022-05-15 09:14:48.122,0 days 00:00:01.606000
77,1,6,in,2022-05-15 09:14:48.260,NaT,NaT
0,1,7,in,2022-05-15 09:03:45.937,2022-05-15 09:03:46.468,0 days 00:00:00.531000
2,1,7,in,2022-05-15 09:05:14.678,2022-05-15 09:05:15.741,0 days 00:00:01.063000
4,1,7,in,2022-05-15 09:05:18.152,2022-05-15 09:05:39.499,0 days 00:00:21.347000
6,1,7,in,2022-05-15 09:05:39.699,2022-05-15 09:05:42.430,0 days 00:00:02.731000
8,1,7,in,2022-05-15 09:05:47.232,2022-05-15 09:05:47.411,0 days 00:00:00.179000
10,1,7,in,2022-05-15 09:05:47.606,2022-05-15 09:05:47.646,0 days 00:00:00.040000
12,1,7,in,2022-05-15 09:05:47.768,2022-05-15 09:05:47.855,0 days 00:00:00.087000
14,1,7,in,2022-05-15 09:08:04.475,2022-05-15 09:08:04.796,0 days 00:00:00.321000
16,1,7,in,2022-05-15 09:08:05.099,2022-05-15 09:08:05.210,0 days 00:00:00.111000
18,1,7,in,2022-05-15 09:08:05.632,2022-05-15 09:08:14.763,0 days 00:00:09.131000
20,1,7,in,2022-05-15 09:08:17.489,2022-05-15 09:08:18.635,0 days 00:00:01.146000
22,1,7,in,2022-05-15 09:08:18.779,2022-05-15 09:08:18.989,0 days 00:00:00.210000
24,1,7,in,2022-05-15 09:08:19.151,2022-05-15 09:08:19.291,0 days 00:00:00.140000
26,1,7,in,2022-05-15 09:08:20.150,2022-05-15 09:08:21.382,0 days 00:00:01.232000
28,1,7,in,2022-05-15 09:08:22.104,2022-05-15 09:08:22.670,0 days 00:00:00.566000
0,1,8,in,2022-05-15 09:03:52.765,2022-05-15 09:03:53.659,0 days 00:00:00.894000
2,1,8,in,2022-05-15 09:03:56.987,2022-05-15 09:03:57.187,0 days 00:00:00.200000
0,8,3,in,2022-05-15 09:03:16.234,2022-05-15 09:04:34.709,0 days 00:01:18.475000
0,8,4,in,2022-05-15 09:03:11.534,2022-05-15 09:03:12.350,0 days 00:00:00.816000
0,8,5,in,2022-05-15 09:14:42.871,2022-05-15 09:14:44.306,0 days 00:00:01.435000
2,8,5,in,2022-05-15 09:14:47.911,2022-05-15 09:14:48.189,0 days 00:00:00.278000
4,8,5,in,2022-05-15 09:14:48.396,2022-05-15 09:14:48.647,0 days 00:00:00.251000
0,8,7,in,2022-05-15 09:05:05.921,2022-05-15 09:07:36.235,0 days 00:02:30.314000
2,8,7,in,2022-05-15 09:07:45.669,2022-05-15 09:07:46.751,0 days 00:00:01.082000
4,8,7,in,2022-05-15 09:08:04.775,2022-05-15 09:10:58.086,0 days 00:02:53.311000
6,8,7,in,2022-05-15 09:10:58.194,2022-05-15 09:11:02.319,0 days 00:00:04.125000
8,8,7,in,2022-05-15 09:11:02.387,2022-05-15 09:11:02.833,0 days 00:00:00.446000
10,8,7,in,2022-05-15 09:11:04.104,2022-05-15 09:11:06.724,0 days 00:00:02.620000
12,8,7,in,2022-05-15 09:11:06.804,2022-05-15 09:11:09.675,0 days 00:00:02.871000
14,8,7,in,2022-05-15 09:11:17.106,2022-05-15 09:11:41.495,0 days 00:00:24.389000
16,8,7,in,2022-05-15 09:11:41.671,2022-05-15 09:11:46.122,0 days 00:00:04.451000
18,8,7,in,2022-05-15 09:11:46.271,2022-05-15 09:11:53.183,0 days 00:00:06.912000
20,8,7,in,2022-05-15 09:11:53.704,2022-05-15 09:12:33.657,0 days 00:00:39.953000
22,8,7,in,2022-05-15 09:12:55.710,2022-05-15 09:12:55.891,0 days 00:00:00.181000
24,8,7,in,2022-05-15 09:14:55.295,2022-05-15 09:14:58.509,0 days 00:00:03.214000
26,8,7,in,2022-05-15 09:14:59.234,2022-05-15 09:15:01.099,0 days 00:00:01.865000
28,8,7,in,2022-05-15 09:15:04.359,2022-05-15 09:15:05.063,0 days 00:00:00.704000
30,8,7,in,2022-05-15 09:15:05.223,2022-05-15 09:15:17.053,0 days 00:00:11.830000
0,8,8,in,2022-05-15 08:45:37.422,2022-05-15 08:50:02.713,0 days 00:04:25.291000
2,8,8,in,2022-05-15 08:50:02.874,2022-05-15 09:01:44.237,0 days 00:11:41.363000
4,8,8,in,2022-05-15 09:01:46.859,2022-05-15 09:01:47.144,0 days 00:00:00.285000
6,8,8,in,2022-05-15 09:01:48.457,2022-05-15 09:01:48.572,0 days 00:00:00.115000
8,8,8,in,2022-05-15 09:01:48.745,2022-05-15 09:01:49.546,0 days 00:00:00.801000
10,8,8,in,2022-05-15 09:01:50.277,2022-05-15 09:01:51.555,0 days 00:00:01.278000
12,8,8,in,2022-05-15 09:02:00.516,2022-05-15 09:02:00.848,0 days 00:00:00.332000
14,8,8,in,2022-05-15 09:02:01.019,2022-05-15 09:02:01.117,0 days 00:00:00.098000
16,8,8,in,2022-05-15 09:02:11.241,2022-05-15 09:02:11.670,0 days 00:00:00.429000
18,8,8,in,2022-05-15 09:02:12.266,2022-05-15 09:02:37.953,0 days 00:00:25.687000
20,8,8,in,2022-05-15 09:02:41.825,2022-05-15 09:02:42.765,0 days 00:00:00.940000
22,8,8,in,2022-05-15 09:02:46.827,2022-05-15 09:02:46.966,0 days 00:00:00.139000
24,8,8,in,2022-05-15 09:04:58.612,2022-05-15 09:05:04.621,0 days 00:00:06.009000
26,8,8,in,2022-05-15 09:07:36.624,2022-05-15 09:07:37.779,0 days 00:00:01.155000
28,8,8,in,2022-05-15 09:07:38.093,2022-05-15 09:07:40.753,0 days 00:00:02.660000
30,8,8,in,2022-05-15 09:07:41.615,2022-05-15 09:07:44.371,0 days 00:00:02.756000
32,8,8,in,2022-05-15 09:08:04.015,2022-05-15 09:08:04.308,0 days 00:00:00.293000
0,8,9,in,2022-05-15 09:03:05.275,2022-05-15 09:03:06.069,0 days 00:00:00.794000
2,8,9,in,2022-05-15 09:04:47.520,2022-05-15 09:04:47.666,0 days 00:00:00.146000
1,9,3,in,2022-05-15 08:48:54.003,2022-05-15 08:53:30.652,0 days 00:04:36.649000
3,9,3,in,2022-05-15 08:53:30.769,2022-05-15 09:00:28.062,0 days 00:06:57.293000
5,9,3,in,2022-05-15 09:00:29.014,2022-05-15 09:01:27.363,0 days 00:00:58.349000
7,9,3,in,2022-05-15 09:01:27.451,2022-05-15 09:01:59.326,0 days 00:00:31.875000
9,9,3,in,2022-05-15 09:02:01.509,2022-05-15 09:03:45.459,0 days 00:01:43.950000
11,9,3,in,2022-05-15 09:05:38.440,2022-05-15 09:05:46.218,0 days 00:00:07.778000
13,9,3,in,2022-05-15 09:05:46.406,2022-05-15 09:08:36.305,0 days 00:02:49.899000
15,9,3,in,2022-05-15 09:12:17.423,2022-05-15 09:12:21.641,0 days 00:00:04.218000
17,9,3,in,2022-05-15 09:12:23.981,NaT,NaT
0,9,4,in,2022-05-15 09:05:17.096,2022-05-15 09:05:19.492,0 days 00:00:02.396000
2,9,4,in,2022-05-15 09:05:19.624,2022-05-15 09:05:30.825,0 days 00:00:11.201000
0,9,5,in,2022-05-15 09:04:02.846,2022-05-15 09:04:47.135,0 days 00:00:44.289000
2,9,5,in,2022-05-15 09:04:49.323,2022-05-15 09:04:57.677,0 days 00:00:08.354000
4,9,5,in,2022-05-15 09:04:57.898,2022-05-15 09:05:01.663,0 days 00:00:03.765000
6,9,5,in,2022-05-15 09:05:01.878,2022-05-15 09:05:01.942,0 days 00:00:00.064000
8,9,5,in,2022-05-15 09:08:52.662,2022-05-15 09:09:03.557,0 days 00:00:10.895000
10,9,5,in,2022-05-15 09:09:22.001,2022-05-15 09:10:02.398,0 days 00:00:40.397000
12,9,5,in,2022-05-15 09:10:03.161,2022-05-15 09:10:14.471,0 days 00:00:11.310000
14,9,5,in,2022-05-15 09:10:15.951,2022-05-15 09:10:19.742,0 days 00:00:03.791000
16,9,5,in,2022-05-15 09:10:20.120,2022-05-15 09:10:27.223,0 days 00:00:07.103000
18,9,5,in,2022-05-15 09:10:27.694,2022-05-15 09:10:44.324,0 days 00:00:16.630000
20,9,5,in,2022-05-15 09:10:44.411,2022-05-15 09:10:48.376,0 days 00:00:03.965000
22,9,5,in,2022-05-15 09:10:49.465,2022-05-15 09:10:52.877,0 days 00:00:03.412000
24,9,5,in,2022-05-15 09:10:53.086,2022-05-15 09:10:56.398,0 days 00:00:03.312000
26,9,5,in,2022-05-15 09:10:56.718,2022-05-15 09:11:24.313,0 days 00:00:27.595000
28,9,5,in,2022-05-15 09:11:24.557,2022-05-15 09:11:28.214,0 days 00:00:03.657000
30,9,5,in,2022-05-15 09:11:30.345,2022-05-15 09:11:31.514,0 days 00:00:01.169000
32,9,5,in,2022-05-15 09:11:31.654,2022-05-15 09:11:31.781,0 days 00:00:00.127000
34,9,5,in,2022-05-15 09:11:31.819,2022-05-15 09:11:40.035,0 days 00:00:08.216000
36,9,5,in,2022-05-15 09:11:40.395,2022-05-15 09:11:41.155,0 days 00:00:00.760000
38,9,5,in,2022-05-15 09:11:42.137,2022-05-15 09:11:59.780,0 days 00:00:17.643000
0,12,3,in,2022-05-15 08:46:22.438,2022-05-15 08:46:36.725,0 days 00:00:14.287000
0,12,4,in,2022-05-15 08:46:41.955,2022-05-15 08:46:42.436,0 days 00:00:00.481000
2,12,4,in,2022-05-15 08:46:42.481,2022-05-15 08:47:11.126,0 days 00:00:28.645000
4,12,4,in,2022-05-15 08:47:11.176,2022-05-15 08:47:19.127,0 days 00:00:07.951000
6,12,4,in,2022-05-15 08:47:19.207,2022-05-15 08:47:20.139,0 days 00:00:00.932000
8,12,4,in,2022-05-15 08:47:20.711,2022-05-15 08:47:25.758,0 days 00:00:05.047000
10,12,4,in,2022-05-15 08:47:25.960,2022-05-15 08:47:31.808,0 days 00:00:05.848000
12,12,4,in,2022-05-15 08:47:31.881,2022-05-15 08:47:56.775,0 days 00:00:24.894000
14,12,4,in,2022-05-15 08:47:57.094,2022-05-15 08:47:57.266,0 days 00:00:00.172000
16,12,4,in,2022-05-15 08:47:57.934,2022-05-15 08:48:21.083,0 days 00:00:23.149000
18,12,4,in,2022-05-15 08:48:21.808,2022-05-15 08:48:53.732,0 days 00:00:31.924000
20,12,4,in,2022-05-15 08:48:53.904,2022-05-15 08:49:41.291,0 days 00:00:47.387000
22,12,4,in,2022-05-15 08:49:41.453,2022-05-15 08:50:03.757,0 days 00:00:22.304000
24,12,4,in,2022-05-15 08:50:09.024,2022-05-15 08:50:51.628,0 days 00:00:42.604000
26,12,4,in,2022-05-15 08:50:51.863,2022-05-15 08:54:58.518,0 days 00:04:06.655000
28,12,4,in,2022-05-15 08:54:58.739,2022-05-15 08:56:56.166,0 days 00:01:57.427000
30,12,4,in,2022-05-15 08:56:56.296,2022-05-15 08:57:18.631,0 days 00:00:22.335000
32,12,4,in,2022-05-15 08:57:18.774,2022-05-15 08:57:50.156,0 days 00:00:31.382000
34,12,4,in,2022-05-15 08:57:50.431,2022-05-15 08:57:50.844,0 days 00:00:00.413000
36,12,4,in,2022-05-15 08:57:51.244,2022-05-15 08:58:04.694,0 days 00:00:13.450000
38,12,4,in,2022-05-15 08:58:07.874,2022-05-15 08:58:08.197,0 days 00:00:00.323000
40,12,4,in,2022-05-15 08:58:09.077,2022-05-15 08:58:35.522,0 days 00:00:26.445000
42,12,4,in,2022-05-15 08:58:35.691,2022-05-15 08:58:49.259,0 days 00:00:13.568000
44,12,4,in,2022-05-15 08:58:49.713,2022-05-15 08:58:51.065,0 days 00:00:01.352000
46,12,4,in,2022-05-15 08:58:51.411,2022-05-15 08:59:23.018,0 days 00:00:31.607000
48,12,4,in,2022-05-15 08:59:23.093,2022-05-15 08:59:28.624,0 days 00:00:05.531000
50,12,4,in,2022-05-15 08:59:30.533,2022-05-15 09:02:51.406,0 days 00:03:20.873000
52,12,4,in,2022-05-15 09:02:56.994,2022-05-15 09:03:00.248,0 days 00:00:03.254000
54,12,4,in,2022-05-15 09:03:01.548,2022-05-15 09:03:47.737,0 days 00:00:46.189000
56,12,4,in,2022-05-15 09:03:48.017,2022-05-15 09:04:23.542,0 days 00:00:35.525000
58,12,4,in,2022-05-15 09:04:24.390,2022-05-15 09:04:25.548,0 days 00:00:01.158000
60,12,4,in,2022-05-15 09:04:26.003,2022-05-15 09:04:29.187,0 days 00:00:03.184000
62,12,4,in,2022-05-15 09:04:29.347,2022-05-15 09:04:39.245,0 days 00:00:09.898000
64,12,4,in,2022-05-15 09:04:39.375,2022-05-15 09:05:07.535,0 days 00:00:28.160000
66,12,4,in,2022-05-15 09:05:07.633,2022-05-15 09:05:21.412,0 days 00:00:13.779000
68,12,4,in,2022-05-15 09:05:21.958,2022-05-15 09:05:23.293,0 days 00:00:01.335000
70,12,4,in,2022-05-15 09:05:24.153,2022-05-15 09:05:39.047,0 days 00:00:14.894000
72,12,4,in,2022-05-15 09:05:39.257,2022-05-15 09:08:39.346,0 days 00:03:00.089000
74,12,4,in,2022-05-15 09:08:39.661,2022-05-15 09:09:15.781,0 days 00:00:36.120000
0,12,5,in,2022-05-15 08:45:11.096,2022-05-15 08:45:12.929,0 days 00:00:01.833000
2,12,5,in,2022-05-15 08:45:13.149,2022-05-15 08:45:17.670,0 days 00:00:04.521000
4,12,5,in,2022-05-15 08:45:18.437,2022-05-15 08:45:18.833,0 days 00:00:00.396000
6,12,5,in,2022-05-15 08:45:19.110,2022-05-15 08:45:21.031,0 days 00:00:01.921000
8,12,5,in,2022-05-15 08:45:21.077,2022-05-15 08:45:38.832,0 days 00:00:17.755000
10,12,5,in,2022-05-15 08:45:38.912,2022-05-15 08:45:48.063,0 days 00:00:09.151000
12,12,5,in,2022-05-15 08:45:48.343,2022-05-15 08:45:53.964,0 days 00:00:05.621000
14,12,5,in,2022-05-15 08:45:59.622,2022-05-15 08:45:59.800,0 days 00:00:00.178000
16,12,5,in,2022-05-15 08:46:06.748,2022-05-15 08:46:12.967,0 days 00:00:06.219000
18,12,5,in,2022-05-15 09:09:26.435,2022-05-15 09:09:27.096,0 days 00:00:00.661000
20,12,5,in,2022-05-15 09:09:27.254,2022-05-15 09:09:34.652,0 days 00:00:07.398000
22,12,5,in,2022-05-15 09:09:35.924,2022-05-15 09:09:41.114,0 days 00:00:05.190000
24,12,5,in,2022-05-15 09:09:41.254,2022-05-15 09:09:45.214,0 days 00:00:03.960000
26,12,5,in,2022-05-15 09:09:49.876,2022-05-15 09:10:22.760,0 days 00:00:32.884000
28,12,5,in,2022-05-15 09:10:25.267,2022-05-15 09:10:41.465,0 days 00:00:16.198000
30,12,5,in,2022-05-15 09:10:43.515,2022-05-15 09:10:43.698,0 days 00:00:00.183000
32,12,5,in,2022-05-15 09:10:43.786,2022-05-15 09:10:50.517,0 days 00:00:06.731000
34,12,5,in,2022-05-15 09:10:50.941,2022-05-15 09:10:52.771,0 days 00:00:01.830000
36,12,5,in,2022-05-15 09:10:55.968,2022-05-15 09:10:56.138,0 days 00:00:00.170000
38,12,5,in,2022-05-15 09:10:56.788,2022-05-15 09:11:05.635,0 days 00:00:08.847000
40,12,5,in,2022-05-15 09:11:09.792,2022-05-15 09:11:17.253,0 days 00:00:07.461000
42,12,5,in,2022-05-15 09:11:17.519,2022-05-15 09:11:17.746,0 days 00:00:00.227000
44,12,5,in,2022-05-15 09:11:18.731,2022-05-15 09:11:19.393,0 days 00:00:00.662000
46,12,5,in,2022-05-15 09:11:20.493,2022-05-15 09:11:57.620,0 days 00:00:37.127000
48,12,5,in,2022-05-15 09:11:57.720,2022-05-15 09:12:50.854,0 days 00:00:53.134000
50,12,5,in,2022-05-15 09:12:54.123,2022-05-15 09:12:57.310,0 days 00:00:03.187000
52,12,5,in,2022-05-15 09:12:57.471,2022-05-15 09:12:57.540,0 days 00:00:00.069000
54,12,5,in,2022-05-15 09:13:00.096,2022-05-15 09:13:49.965,0 days 00:00:49.869000
56,12,5,in,2022-05-15 09:13:50.722,2022-05-15 09:14:10.330,0 days 00:00:19.608000
58,12,5,in,2022-05-15 09:14:12.462,2022-05-15 09:14:20.026,0 days 00:00:07.564000
60,12,5,in,2022-05-15 09:14:20.065,2022-05-15 09:14:20.891,0 days 00:00:00.826000
62,12,5,in,2022-05-15 09:14:21.081,2022-05-15 09:14:21.381,0 days 00:00:00.300000
64,12,5,in,2022-05-15 09:14:22.032,2022-05-15 09:14:22.568,0 days 00:00:00.536000
66,12,5,in,2022-05-15 09:14:23.632,2022-05-15 09:15:12.696,0 days 00:00:49.064000
68,12,5,in,2022-05-15 09:15:12.760,2022-05-15 09:15:12.947,0 days 00:00:00.187000
70,12,5,in,2022-05-15 09:15:12.992,2022-05-15 09:15:13.452,0 days 00:00:00.460000
72,12,5,in,2022-05-15 09:15:16.558,2022-05-15 09:15:17.338,0 days 00:00:00.780000
74,12,5,in,2022-05-15 09:15:17.834,NaT,NaT
1,13,3,in,2022-05-15 09:06:10.264,2022-05-15 09:08:36.715,0 days 00:02:26.451000
3,13,3,in,2022-05-15 09:08:40.667,2022-05-15 09:08:42.067,0 days 00:00:01.400000
5,13,3,in,2022-05-15 09:08:42.732,2022-05-15 09:14:06.001,0 days 00:05:23.269000
0,13,4,in,2022-05-15 09:04:44.692,2022-05-15 09:04:45.208,0 days 00:00:00.516000
0,13,5,in,2022-05-15 09:14:37.069,2022-05-15 09:14:37.344,0 days 00:00:00.275000
2,13,5,in,2022-05-15 09:14:37.385,2022-05-15 09:14:37.686,0 days 00:00:00.301000
4,13,5,in,2022-05-15 09:14:37.786,2022-05-15 09:14:47.886,0 days 00:00:10.100000
6,13,5,in,2022-05-15 09:14:47.929,2022-05-15 09:14:56.718,0 days 00:00:08.789000
0,13,6,in,2022-05-15 09:15:05.839,2022-05-15 09:15:05.932,0 days 00:00:00.093000
2,13,6,in,2022-05-15 09:15:13.876,NaT,NaT
0,13,7,in,2022-05-15 09:05:13.717,2022-05-15 09:05:13.951,0 days 00:00:00.234000
2,13,7,in,2022-05-15 09:05:17.809,2022-05-15 09:05:47.326,0 days 00:00:29.517000
4,13,7,in,2022-05-15 09:05:48.073,2022-05-15 09:05:48.220,0 days 00:00:00.147000
0,13,8,in,2022-05-15 09:05:02.425,2022-05-15 09:05:02.492,0 days 00:00:00.067000
2,13,8,in,2022-05-15 09:05:08.653,2022-05-15 09:05:09.421,0 days 00:00:00.768000
1,14,3,in,2022-05-15 08:48:27.949,2022-05-15 08:51:47.134,0 days 00:03:19.185000
3,14,3,in,2022-05-15 08:52:01.432,2022-05-15 08:54:23.418,0 days 00:02:21.986000
5,14,3,in,2022-05-15 08:54:28.747,2022-05-15 08:56:11.804,0 days 00:01:43.057000
7,14,3,in,2022-05-15 08:56:33.912,2022-05-15 08:59:20.917,0 days 00:02:47.005000
9,14,3,in,2022-05-15 09:01:00.407,2022-05-15 09:03:10.273,0 days 00:02:09.866000
11,14,3,in,2022-05-15 09:03:44.839,2022-05-15 09:04:17.561,0 days 00:00:32.722000
13,14,3,in,2022-05-15 09:05:38.753,2022-05-15 09:05:39.396,0 days 00:00:00.643000
15,14,3,in,2022-05-15 09:05:39.938,2022-05-15 09:07:30.628,0 days 00:01:50.690000
17,14,3,in,2022-05-15 09:09:06.115,2022-05-15 09:09:25.949,0 days 00:00:19.834000
19,14,3,in,2022-05-15 09:10:00.820,2022-05-15 09:10:04.466,0 days 00:00:03.646000
21,14,3,in,2022-05-15 09:10:48.127,2022-05-15 09:10:53.422,0 days 00:00:05.295000
23,14,3,in,2022-05-15 09:10:58.134,2022-05-15 09:11:03.489,0 days 00:00:05.355000
25,14,3,in,2022-05-15 09:11:07.270,2022-05-15 09:11:10.050,0 days 00:00:02.780000
0,14,4,in,2022-05-15 08:56:15.974,2022-05-15 08:56:28.664,0 days 00:00:12.690000
2,14,4,in,2022-05-15 08:56:29.687,2022-05-15 08:56:30.058,0 days 00:00:00.371000

In [207]:
for i in range(1,len(a_group)):
    if df['status'].iloc[i] == 'in':
        continue
    else:        
        date_1 = a_group['Time'].iloc[i-1]
        date_2 = a_group['Time'].iloc[i]

        start = datetime.strptime(date_1, date_format_str)
        end =   datetime.strptime(date_2, date_format_str)
        # Get interval between two datetimes as timedelta object
        diff = (end - start)
        total_diff += diff.total_seconds()
        

# Get the interval in minutes
diff_in_minutes = diff.total_seconds() / 60
print('Difference between two datetimes in second:')
print(total_diff)
print('Difference between two datetimes in minutes:')
print(diff_in_minutes)
print (diff)


print (date_1)
print (date_2)
print (a_group.shape)

0:00:21.309000
0:00:00.191000
Difference between two datetimes in second:
2041.5560000000019
Difference between two datetimes in minutes:
0.0031833333333333336
0:00:00.191000
2022-05-15 09:15:03.019
2022-05-15 09:15:03.210
(4, 4)

In [172]:
x=df.groupby(["feed_id",'zone_id']).get_group((22, 8))
x

     feed_id  zone_id status                     Time
144       22        8     in  2022-05-15 08:47:30.040
145       22        8    out  2022-05-15 08:47:30.711
149       22        8     in  2022-05-15 08:47:32.295
151       22        8    out  2022-05-15 08:47:32.715
153       22        8     in  2022-05-15 08:47:32.795
154       22        8    out  2022-05-15 08:47:33.010
159       22        8     in  2022-05-15 08:47:43.246
160       22        8    out  2022-05-15 08:47:43.381
161       22        8     in  2022-05-15 08:47:43.721
162       22        8    out  2022-05-15 08:47:43.807

In [188]:
a = []         
a

#result=pd.DataFrame(columns=['time_diff'])
#result["time_diff"] = pd.to_datetime(result)
#result

[]

In [209]:
from datetime import datetime
for i in range(1,len(x)):
    if df['status'].iloc[i] == 'in':
        continue
    else:        
        date_1 = df['Time'].iloc[i-1]
        date_2 = df['Time'].iloc[i]

        start = datetime.strptime(date_1, date_format_str)
        end =   datetime.strptime(date_2, date_format_str)
        # Get interval between two datetimes as timedelta object
        diff = (end - start)
        #result=result.append(diff)
        total_diff += diff.total_seconds()
        print(str(diff))



        

# Get the interval in minutes
diff_in_minutes = diff.total_seconds() / 60
print('Difference between two datetimes in second:')
print(total_diff)
print('Difference between two datetimes in minutes:')
print(diff_in_minutes)

print(date_1)
print(date_2)
type(total_diff)

0:00:00.489000
0:00:00.054000
0:00:03.998000
0:00:00.244000
Difference between two datetimes in second:
2049.5800000000017
Difference between two datetimes in minutes:
0.004066666666666666
2022-05-15 08:45:04.335
2022-05-15 08:45:04.579

float